version: '3.9'

networks:
  app-network-public:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: db-sqlserver
    networks:
      - app-network-public
    restart: always
    env_file:
      - sqlserver.env
      - sapassword.env
    ports:
      - '1433:1433'
    volumes:
      - sql-server-data:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - /c/docker/shared:/usr/shared